image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/socshared-auth-service-1.0.0-SNAPSHOT.jar

docker-build:
  stage: docker-build
  script:
    - sudo docker build -t $CI_DOCKER_LOGIN/socshared-auth-service .

docker-push:
  stage: docker-push
  script:
    - sudo docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - sudo docker push $CI_DOCKER_LOGIN/socshared-auth-service

docker-deploy-swarm:
  stage: docker-deploy-swarm
  script:
    - touch .env_session
    - echo "SPRING_PROFILE=dev" >> .env_session
    - echo "POSTGRES_USER=admin" >> .env_session
    - echo "POSTGRES_PASSWORD=admin" >> .env_session
    - echo "POSTGRES_HOST=auth_postgres_db" >> .env_session
    - echo "POSTGRES_DB=auth" >> .env_session
    - echo "SECRET_JWT_KEY=$SECRET_JWT_KEY" >> .env_session
    - sudo docker stack deploy -c docker-compose.yaml socshared
