/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ml.socshared.service.auth;

import ml.socshared.service.auth.integration.AbstractIT;
import org.junit.Test;

public class ApplicationContextTest extends AbstractIT {

    @Test
    public void checkContextStarts() {

    }

}
